#ifndef AG_VERSION_H
#define AG_VERSION_H

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 7

#define AG_STRINGIFY_(x) #x
#define AG_STRINGIFY(x) AG_STRINGIFY_(x)

#define APP_VERSION_STRING \
    AG_STRINGIFY(APP_VERSION_MAJOR) "." \
    AG_STRINGIFY(APP_VERSION_MINOR) "." \
    AG_STRINGIFY(APP_VERSION_PATCH)

#endif /* AG_VERSION_H */
